version: "3"

networks:
  graphqlauth:

services:
  node:
    container_name: graphql-auth-server
    networks:
      - graphqlauth
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
